repos:
  # a set of useful Python-based pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: check-added-large-files
        args: ["--maxkb=1000240"]
      - id: debug-statements
      - id: detect-private-key
      - id: pretty-format-json
        args: ["--autofix"]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
        files: ^config/

  # ruff for Python linting and formatting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.6"
    hooks:
      - id: ruff
        args: [ --fix ]
        types_or: [python, pyi, jupyter]  # Add jupyter to linting
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  # shellcheck-py for linting shell files
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
