version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: raggaeton-tia-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/raggaeton


  # frontend:
  #   image: raggaeton-tia-frontend:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000
  #     - REACT_APP_API_KEY=${API_KEY}
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend
