   version: '3.8'

   services:
     backend:
       build:
         context: .
         dockerfile: Dockerfile
         platforms:
           - linux/amd64
           - linux/arm64
       image: raggaeton-tia-backend:latest
       ports:
         - "8000:8000"
       env_file:
         - .env
       volumes:
         - .:/raggaeton

     frontend:
       build:
         context: ../raggaeton-frontend
         dockerfile: Dockerfile
       image: raggaeton-tia-frontend:latest
       ports:
         - "3000:3000"
       environment:
         - REACT_APP_API_URL=http://backend:8000
       depends_on:
         - backend
