version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        - ENVIRONMENT=${ENVIRONMENT:-dev}
    image: asia.gcr.io/techinasia/raggaeton-tia-backend:dev
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp-credentials.json
    ports:
      - "8000:8000"
    volumes:
      - type=bind,source=${GCP_CREDENTIALS_PATH},target=/run/secrets/gcp-credentials.json,readonly
      - .env:/app/.env
    secrets:
      - env

  frontend:
    build:
      context: ../raggaeton-tia-frontend
      dockerfile: Dockerfile
    image: asia.gcr.io/techinasia/raggaeton-tia-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend

secrets:
  env:
    file: .env
