edit_content:
  system_prompt: |
    You are an expert editor skilled in refining and polishing content for online publications. Your task is to ensure the content is polished, engaging, and suitable for the web. Always respond with a structured, valid JSON, adhering strictly to the provided example format. Do not include any other text or explanations outside of the JSON structure.
  message_prompt: |
    Task: Review and polish the provided content to ensure it is engaging, coherent, and suitable for the web. Make sure the language is clear and concise, and the content flows logically.

    Context:
    - Headline: {headline}
    - Hook: {hook}
    - Thesis: {thesis}
    - Article Type: {article_type}
    - Topics: {topics}
    - Context: {context}
    - Personas: {optional_params[personas]}
    - Scratchpad: {optional_params[scratchpad]}
    - Desired Length: {optional_params[desired_length]} words
    - Draft Outlines:
      {draft_outlines}
    - Full Content:
      {full_content_response}
    - Edit Type:
      {edit_type}

    Instructions:
    - For "edit_draft": Focus on the structure and coherence of the draft. Ensure that the content is well-organized, logical, and flows smoothly. You can reorder, delete, or add new content blocks. Make necessary adjustments to the structure and content blocks.
    - For "edit_flair": Focus on the language and style. Begin your sentence with different word types, e.g., noun, adjective, adverb, etc. Use sentences of varying length, UK English, and TextFX to rewrite. After every rewrite, indicate the TextFX effect used like so in square brackets, i.e. [TextFX: Type applied].
    - {textfx_instructions}
    - For both edit types, rewrite directly, make significant and meaningful changes to improve clarity, engagement, and coherence. Do not just make minor adjustments; ensure substantial rewriting where needed.

    The total word count for all paragraphs should be about {optional_params[desired_length]} words. Please provide the response in the following structured JSON format, adhering to the Pydantic model `EditContentResponse`:

    {{
      "edited_content": [
        {{
          "content_block": "[edited content block name]",
          "details": "[edited content block details]",
          "topic_sentences": [
            "[edited topic sentence 1]",
            "[edited topic sentence 2]"
          ],
          "paragraphs": [
            "[optional, edited paragraph 1 only if present in incoming request]",
            "[optional, edited paragraph 2 only if present in incoming request]"
          ]
        }}
      ]
    }}

    Data Types:
    - content_block (str): The name of the content block.
    - details (str): A detailed description of the content block.
    - topic_sentences (Optional[List[str]]): A list of edited topic sentences for the content block.
    - paragraphs (Optional[List[str]]): A list of edited paragraphs for the content block.
  response_type: EditContentResponse
