# config.yaml
table_url: "https://zbqrnhxgqdhpfurfnoor.supabase.co"
table_posts: "tia_posts"
table_batch_log: "tia_batch_log"
table_page_status: "tia_page_status"
test_table: "test_table"
supabase_host: "aws-0-ap-southeast-1.pooler.supabase.com"
supabase_user: "postgres.zbqrnhxgqdhpfurfnoor"
supabase_pw: "15ZJm1ADzRS1RjAl"
index_name: "test_collection"

document:
  chunk_size: [512, 256]
  overlap: [50, 20]

embedding:
  models:
    - "Alibaba-NLP/gte-base-en-v1.5" #768
    - "Alibaba-NLP/gte-large-en-v1.5" #1024
    - "WhereIsAI/UAE-Large-V1" #1024
    - "GritLM/GritLM-7B" #4096
  dimension: [256, 512, 1024]
  batch_size: 100

llm:
  models:
    - model_name: "gpt-4o"
      params:
        temperature: 0.1
        frequency_penalty: 0.0
        presence_penalty: 0.0
      api_key_env: "OPENAI_API_KEY"
      prompt_templates:
        generate_qa:
          system_message: ""
          message: "Your custom message here"
    - model_name: "claude-3-opus-20240229"
      params:
        max_tokens: 1000
        temperature: 0.1
        system_message: "You are an intelligent assistant."
      api_key_env: "CLAUDE_API_KEY"
    - model_name: "claude-3-haiku-20240307"
      params:
        temperature: 0.1
        system_message: "You are an intelligent assistant."
      api_key_env: "CLAUDE_API_KEY"

logging:
  level: "DEBUG"
  file: "log/app.log"  # Relative path from project root, leave empty to not save
  enable_console: true
