# config.yaml
table_url: "https://zbqrnhxgqdhpfurfnoor.supabase.co"
table_name: "tia_posts"
test_table_name: "test_table"

embedding:
  models:
    - "BAAI/bge-base-en-v1.5"
    - "sentence-transformers/all-mpnet-base-v2"
    - "jinaai/jina-embeddings-v2-small-en"
  size: [256, 512]

llm:
  models:
    - model_name: "gpt-4-1106-preview"
      params:
        temperature: 0.8
        frequency_penalty: 0.0
        presence_penalty: 0.0
        system_message: "You are a helpful assistant."
      api_key_env: "OPENAI_API_KEY"
      prompt_templates:
        generate_qa:
          system_message: ""
          message: "Your custom message here"
